import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthProvider from '../../provider/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

function RootLayoutWithProvider(
  props: React.ComponentProps<typeof RootLayout>
) {
  return (
    <NextAuthProvider>
        <RootLayout {...props} />
    </NextAuthProvider>
      
  );
}

export default RootLayoutWithProvider;
